name: Lighthouse Performance Audit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:8000/tr/index.html
            http://localhost:8000/tr/hamam.html
            http://localhost:8000/tr/masajlar.html
          serverStartCommand: npx http-server . -p 8000
          serverWaitUntilReady: true
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
          budgetPath: ./budget.json