/* AUTO-GENERATED by tools/nv-build-pack-index.js
   Source: NEUROVA_PROMPT/packs/pack.*.js
   Do not edit manually (edit packs instead).
*/
(function () {
  "use strict";
  window.NV_PACK_LIST = [
  "./packs/pack.ayurveda.js",
  "./packs/pack.brand-look.js",
  "./packs/pack.hamam.js",
  "./packs/pack.kids.family.ascii.js",
  "./packs/pack.kids.js",
  "./packs/pack.kids.premium.js",
  "./packs/pack.massage.js",
  "./packs/pack.recovery.js",
  "./packs/pack.seasonal-detox.js",
  "./packs/pack.signature-family-teen.js",
  "./packs/pack.signature.js",
  "./packs/pack.teen.js"
  ];
})();
