/* pack.kids.family.ascii.js */ (function () {
  "use strict";
  const KEY = "KIDS_FAMILY_ASCII";
  window.NV_PROMPT_PACKS = window.NV_PROMPT_PACKS || {};

  window.NV_PROMPT_PACKS[KEY] = [
    {
      id: "KIDS_01",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Kids Mini Relax Masaji",
      title_tr: "Kids Mini Relax Masaji",
      title_en: "Kids Mini Relax Massage",
      prompt: "Kids mini relax massage concept, family-friendly spa atmosphere, warm safe composition, soft light, quiet luxury",
      prompt_tr: "Kids mini relax masaji konsepti, aile dostu spa atmosferi, sicak ve guvenli kompozisyon, soft light, quiet luxury",
      prompt_en: "Kids mini relax massage concept, family-friendly spa atmosphere, warm safe composition, soft light, quiet luxury",
      negative: "child close-up, nudity, suggestive angles",
      tags: ["kids", "family", "relax", "spa"],
      lang: { tr: "Kids mini relax masaji konsepti, aile dostu spa atmosferi, sicak ve guvenli kompozisyon, soft light, quiet luxury", en: "Kids mini relax massage concept, family-friendly spa atmosphere, warm safe composition, soft light, quiet luxury" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; represent via objects/room setup only"
    },
    {
      id: "KIDS_02",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Teen Calm Program",
      title_tr: "Teen Calm Program",
      title_en: "Teen Calm Program",
      prompt: "Teen calm program concept, calm modern spa room, gentle ritual feeling, minimal aesthetic",
      prompt_tr: "Teen calm program konsepti, sakin ve modern spa odasi, nazik rituel hissi, minimal estetik",
      prompt_en: "Teen calm program concept, calm modern spa room, gentle ritual feeling, minimal aesthetic",
      negative: "teen face close-up, nudity",
      tags: ["teen", "calm", "spa"],
      lang: { tr: "Teen calm program konsepti, sakin ve modern spa odasi, nazik rituel hissi, minimal estetik", en: "Teen calm program concept, calm modern spa room, gentle ritual feeling, minimal aesthetic" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; use room details only"
    },
    {
      id: "KIDS_03",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Family Hamam Deneyimi",
      title_tr: "Family Hamam Deneyimi",
      title_en: "Family Hammam Experience",
      prompt: "Family hammam experience concept, marble and steam atmosphere, family-safe composition, quiet luxury",
      prompt_tr: "Family hamam deneyimi konsepti, mermer ve buhar atmosferi, aile dostu guvenli kompozisyon, quiet luxury",
      prompt_en: "Family hammam experience concept, marble and steam atmosphere, family-safe composition, quiet luxury",
      negative: "kids shown, nudity, crowded scene",
      tags: ["family", "hamam", "experience"],
      lang: { tr: "Family hamam deneyimi konsepti, mermer ve buhar atmosferi, aile dostu guvenli kompozisyon, quiet luxury", en: "Family hammam experience concept, marble and steam atmosphere, family-safe composition, quiet luxury" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; architectural and objects only"
    },
    {
      id: "KIDS_04",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Mom and Daughter Mini Spa",
      title_tr: "Mom and Daughter Mini Spa",
      title_en: "Mom and Daughter Mini Spa",
      prompt: "Mom and daughter mini spa concept, gentle warm atmosphere, cotton towels, soft light, premium spa feeling",
      prompt_tr: "Anne ve kiz mini spa konsepti, nazik ve sicak atmosfer, pamuk havlu, soft light, premium spa hissi",
      prompt_en: "Mom and daughter mini spa concept, gentle warm atmosphere, cotton towels, soft light, premium spa feeling",
      negative: "minor depiction, intimacy",
      tags: ["family", "mini", "spa"],
      lang: { tr: "Anne ve kiz mini spa konsepti, nazik ve sicak atmosfer, pamuk havlu, soft light, premium spa hissi", en: "Mom and daughter mini spa concept, gentle warm atmosphere, cotton towels, soft light, premium spa feeling" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; avoid people, show setup only"
    },
    {
      id: "KIDS_05",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Dad and Son Chill Time",
      title_tr: "Dad and Son Chill Time",
      title_en: "Dad and Son Chill Time",
      prompt: "Dad and son chill time concept, family-friendly resting area, clean modern spa aesthetic",
      prompt_tr: "Baba ve ogul chill time konsepti, aile dostu dinlenme alani, sade ve modern spa estetigi",
      prompt_en: "Dad and son chill time concept, family-friendly resting area, clean modern spa aesthetic",
      negative: "minor depiction, nudity",
      tags: ["family", "rest", "chill"],
      lang: { tr: "Baba ve ogul chill time konsepti, aile dostu dinlenme alani, sade ve modern spa estetigi", en: "Dad and son chill time concept, family-friendly resting area, clean modern spa aesthetic" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; environment only"
    },
    {
      id: "KIDS_06",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Kids First Hamam Concept",
      title_tr: "Kids First Hamam Concept",
      title_en: "Kids First Hammam Concept",
      prompt: "Kids first hammam concept, soft foam theme, safe minimal marble atmosphere",
      prompt_tr: "Kids first hamam konsepti, yumusak kopuk temasi, guvenli ve sade mermer atmosfer",
      prompt_en: "Kids first hammam concept, soft foam theme, safe minimal marble atmosphere",
      negative: "children shown, nudity",
      tags: ["kids", "hamam", "foam"],
      lang: { tr: "Kids first hamam konsepti, yumusak kopuk temasi, guvenli ve sade mermer atmosfer", en: "Kids first hammam concept, soft foam theme, safe minimal marble atmosphere" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; foam and towels as objects only"
    },
    {
      id: "KIDS_07",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Family Mini Relax Lounge",
      title_tr: "Family Mini Relax Lounge",
      title_en: "Family Mini Relax Lounge",
      prompt: "Family mini relax lounge, warm tones, cotton towels, herbal tea service, quiet luxury",
      prompt_tr: "Aile icin mini relax lounge, sicak tonlar, pamuk havlu, bitkisel cay servisi, quiet luxury",
      prompt_en: "Family mini relax lounge, warm tones, cotton towels, herbal tea service, quiet luxury",
      negative: "kids faces, crowded lounge",
      tags: ["family", "lounge", "relax"],
      lang: { tr: "Aile icin mini relax lounge, sicak tonlar, pamuk havlu, bitkisel cay servisi, quiet luxury", en: "Family mini relax lounge, warm tones, cotton towels, herbal tea service, quiet luxury" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; still-life lounge scene"
    },
    {
      id: "KIDS_08",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Teen Sport Recovery Concept",
      title_tr: "Teen Sport Recovery Concept",
      title_en: "Teen Sport Recovery Concept",
      prompt: "Teen sport recovery concept, light recovery feeling, clean minimal spa room",
      prompt_tr: "Teen sport recovery konsepti, hafif toparlanma hissi, temiz ve minimal spa odasi",
      prompt_en: "Teen sport recovery concept, light recovery feeling, clean minimal spa room",
      negative: "teen depiction, medical claims",
      tags: ["teen", "sport", "recovery"],
      lang: { tr: "Teen sport recovery konsepti, hafif toparlanma hissi, temiz ve minimal spa odasi", en: "Teen sport recovery concept, light recovery feeling, clean minimal spa room" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; show tools/room only"
    },
    {
      id: "KIDS_09",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Family Asian Foam and Relax",
      title_tr: "Family Asian Foam and Relax",
      title_en: "Family Asian Foam and Relax",
      prompt: "Family Asian Foam and Relax package concept, foam theme, calm family lounge area, premium spa feeling",
      prompt_tr: "Family asian foam and relax paketi konsepti, kopuk temasi, sakin aile lounge alani, premium spa hissi",
      prompt_en: "Family Asian Foam and Relax package concept, foam theme, calm family lounge area, premium spa feeling",
      negative: "minors shown, nudity",
      tags: ["family", "foam", "asia", "package"],
      lang: { tr: "Family asian foam and relax paketi konsepti, kopuk temasi, sakin aile lounge alani, premium spa hissi", en: "Family Asian Foam and Relax package concept, foam theme, calm family lounge area, premium spa feeling" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; environment and objects only"
    },
    {
      id: "KIDS_10",
      category: "Kids and Family",
      region: "Kids and Family",
      role: "Photographer",
      title: "Kids Chocolate Dream Concept",
      title_tr: "Kids Chocolate Dream Concept",
      title_en: "Kids Chocolate Dream Concept",
      prompt: "Kids chocolate dream concept, warm cocoa tones, sweet yet premium spa aesthetic, minimal still-life presentation",
      prompt_tr: "Kids chocolate dream konsepti, sicak kakao tonlari, tatli ama premium spa estetigi, minimal still-life sunum",
      prompt_en: "Kids chocolate dream concept, warm cocoa tones, sweet yet premium spa aesthetic, minimal still-life presentation",
      negative: "food ad look, kids shown",
      tags: ["kids", "chocolate", "dream", "spa"],
      lang: { tr: "Kids chocolate dream konsepti, sicak kakao tonlari, tatli ama premium spa estetigi, minimal still-life sunum", en: "Kids chocolate dream concept, warm cocoa tones, sweet yet premium spa aesthetic, minimal still-life presentation" },
      langCode: "TR/EN",
      safeNote: "No minors depicted; still-life concept only"
    }
  ];
})();
